name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release
  CC: clang
  CXX: clang++


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install packages
      run: sudo apt-get install libxrandr-dev xorg-dev libglu1-mesa-dev

    - uses: actions/checkout@v2
      
    - name: "Checkout submodules"
      run: git submodule update --init --recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
     
